version: "2"
linters:
  default: none
  enable:
    - dogsled
    - dupl
    - errcheck
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 120
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - hugeParam
        - rangeValCopy
        - exitAfterDefer
        - whyNoLint
        - singleCaseSwitch
        - commentedOutCode
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 140
    misspell:
      locale: US
    revive:
      rules:
        - name: unused-parameter
          severity: warning
          disabled: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - gocritic
        text: commentedOutCode
        source: SHA1
      - linters:
          - gochecknoglobals
        source: embed\.FS
      - linters:
          - lll
        source: //go:generate
      - linters:
          - dupl
          - errcheck
          - funlen
          - gochecknoglobals
          - gocognit
          - goconst
          - gocyclo
          - gosec
          - lll
          - scopelint
        path: _test\.go
      - linters:
          - govet
        text: declaration of "(err|ctx|log)"
      - linters:
          - golint
        path: internal\.go
        text: should have.+comment
      - linters:
          - golint
          - staticcheck
        text: underscores? in package names?
      - linters:
          - staticcheck
        text: 'SA1019: (telegram|client).+ is deprecated:'
      - linters:
          - revive
        text: 'var-naming: don''t use an underscore in package name'
      - linters:
          - gosec
        text: 'G115: integer overflow conversion'
      - linters:
          - staticcheck
        path: vault/client
        text: deprecated
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/gotd/
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
